export enum AttributeKeys {
  LIMIT = "limit",
  SORT = "sort",
  SKIP = "skip",
  IN = "in",
  GT = "gt",
  LT = "lt",
  AND = "and",
  OR = "or",
  NOR = "nor",
  SET = "set",
  ID = "id",
  CREATED_AT = "createdAt",
  UPDATED_AT = "updatedAt",
}
